extends SceneTree

const Content = preload("res://scripts/content_db.gd")
const PackContract = preload("res://scripts/content/planet_content_pack.gd")
const Registry = preload("res://scripts/content/content_pack_registry.gd")
const Dustball = preload("res://scripts/content/packs/dustball_prime.gd")
const Congelaria = preload("res://scripts/content/packs/congelaria_sa.gd")
const Micelia = preload("res://scripts/content/packs/micelia_404.gd")
const FerroVelho = preload("res://scripts/content/packs/ferro_velho_omega.gd")
const Cassino = preload("res://scripts/content/packs/cassino_quasar.gd")
const Aeropolis = preload("res://scripts/content/packs/aeropolis_penhora.gd")
const ArquivoAbissal = preload("res://scripts/content/packs/arquivo_abissal_n9.gd")
const Verdantia = preload("res://scripts/content/packs/verdantia_patenteada.gd")
const Caldeira = preload("res://scripts/content/packs/caldeira_garantia.gd")
const CondominioLunar = preload("res://scripts/content/packs/condominio_lunar_7.gd")
const NecropoleSolar = preload("res://scripts/content/packs/necropole_solar_umbral.gd")
const CentralTempestades = preload("res://scripts/content/packs/central_tempestades_24h.gd")
const MuseuAmanha = preload("res://scripts/content/packs/museu_amanha_obsoleto.gd")
const BibliotecaSilencio = preload("res://scripts/content/packs/biblioteca_silencio_taxado.gd")
const ResortHorizonte = preload("res://scripts/content/packs/resort_horizonte_eventos.gd")
const TribunalClones = preload("res://scripts/content/packs/tribunal_clones_nao_autorizados.gd")
const MosteiroGravidade = preload("res://scripts/content/packs/mosteiro_gravidade_reversa.gd")
const MercadoMemorias = preload("res://scripts/content/packs/mercado_memorias_usadas.gd")
const EstaleiroTemporal = preload("res://scripts/content/packs/estaleiro_naufragios_temporais.gd")
const BolsaLuas = preload("res://scripts/content/packs/bolsa_luas_fracionadas.gd")
const FabricaSois = preload("res://scripts/content/packs/fabrica_sois_recondicionados.gd")
const ClinicaPlanetas = preload("res://scripts/content/packs/clinica_planetas_descontinuados.gd")
const CorreioMinhoca = preload("res://scripts/content/packs/correio_buracos_minhoca.gd")
const AquarioOceanos = preload("res://scripts/content/packs/aquario_oceanos_confiscados.gd")
const CentralSonhos = preload("res://scripts/content/packs/central_sonhos_penhorados.gd")

var failures := 0


func _init() -> void:
	check(Registry.validation_errors().is_empty(), "registered planet packs satisfy the complete content contract")
	check(Registry.PACK_SCRIPTS.size() == 25, "the registry contains all twenty-five current canonical planet packs")
	check(Registry.PLANETS.size() == 25, "the registry composes all twenty-five planets")
	check(Registry.TARGETS.size() == 100, "the registry composes all 100 targets")
	check(Registry.HUNT_EVENTS.size() == 50, "the registry composes all 50 hunt incidents")
	check(Registry.pack_for_planet("dustball_prime") == Dustball.PACK, "registry resolves the canonical Dustball pack")
	check(Registry.pack_for_planet("congelaria_sa") == Congelaria.PACK, "registry resolves the canonical Congelaria pack")
	check(Registry.pack_for_planet("micelia_404") == Micelia.PACK, "registry resolves the canonical Micelia pack")
	check(Registry.pack_for_planet("ferro_velho_omega") == FerroVelho.PACK, "registry resolves the canonical Ferro-Velho pack")
	check(Registry.pack_for_planet("cassino_quasar") == Cassino.PACK, "registry resolves the canonical Cassino pack")
	check(Registry.pack_for_planet("aeropolis_penhora") == Aeropolis.PACK, "registry resolves the canonical Aeropolis pack")
	check(Registry.pack_for_planet("arquivo_abissal_n9") == ArquivoAbissal.PACK, "registry resolves the canonical Arquivo Abissal pack")
	check(Registry.pack_for_planet("verdantia_patenteada") == Verdantia.PACK, "registry resolves the canonical Verdantia pack")
	check(Registry.pack_for_planet("caldeira_garantia") == Caldeira.PACK, "registry resolves the canonical Warranty Caldera pack")
	check(Registry.pack_for_planet("condominio_lunar_7") == CondominioLunar.PACK, "registry resolves the canonical Lunar Estate pack")
	check(Registry.pack_for_planet("necropole_solar_umbral") == NecropoleSolar.PACK, "registry resolves the canonical Umbral Solar Necropolis pack")
	check(Registry.pack_for_planet("central_tempestades_24h") == CentralTempestades.PACK, "registry resolves the canonical 24h Storm Center pack")
	check(Registry.pack_for_planet("museu_amanha_obsoleto") == MuseuAmanha.PACK, "registry resolves the canonical Museum of Obsolete Tomorrows pack")
	check(Registry.pack_for_planet("biblioteca_silencio_taxado") == BibliotecaSilencio.PACK, "registry resolves the canonical Taxed Silence Library pack")
	check(Registry.pack_for_planet("resort_horizonte_eventos") == ResortHorizonte.PACK, "registry resolves the canonical Event Horizon Resort pack")
	check(Registry.pack_for_planet("tribunal_clones_nao_autorizados") == TribunalClones.PACK, "registry resolves the canonical Unauthorized Clone Court pack")
	check(Registry.pack_for_planet("mosteiro_gravidade_reversa") == MosteiroGravidade.PACK, "registry resolves the canonical Reverse Gravity Monastery pack")
	check(Registry.pack_for_planet("mercado_memorias_usadas") == MercadoMemorias.PACK, "registry resolves the canonical Used Memory Market pack")
	check(Registry.pack_for_planet("estaleiro_naufragios_temporais") == EstaleiroTemporal.PACK, "registry resolves the canonical Temporal Wreck Shipyard pack")
	check(Registry.pack_for_planet("bolsa_luas_fracionadas") == BolsaLuas.PACK, "registry resolves the canonical Fractional Moon Exchange pack")
	check(Registry.pack_for_planet("fabrica_sois_recondicionados") == FabricaSois.PACK, "registry resolves the canonical Refurbished Sun Factory pack")
	check(Registry.pack_for_planet("clinica_planetas_descontinuados") == ClinicaPlanetas.PACK, "registry resolves the canonical Discontinued Planet Clinic pack")
	check(Registry.pack_for_planet("correio_buracos_minhoca") == CorreioMinhoca.PACK, "registry resolves the canonical Wormhole Post pack")
	check(Registry.pack_for_planet("aquario_oceanos_confiscados") == AquarioOceanos.PACK, "registry resolves the canonical Confiscated Oceans Aquarium pack")
	check(Registry.pack_for_planet("central_sonhos_penhorados") == CentralSonhos.PACK, "registry resolves the canonical Repossessed Dreams Center pack")
	check(Registry.pack_for_planet("unknown").is_empty(), "unknown planet packs fail closed")
	var detached := Registry.pack_for_planet("dustball_prime")
	detached.planet.name = "MUTATED"
	check(str(Registry.pack_for_planet("dustball_prime").planet.name) == "Dustball Prime", "registry callers cannot mutate canonical pack data")

	check(Content.PLANET == Dustball.PLANET, "ContentDB preserves the public starter planet constant")
	check(Content.PLANETS == Registry.PLANETS, "ContentDB exposes the registry's canonical planet composition")
	check(Content.TARGETS == Registry.TARGETS, "ContentDB exposes the registry's canonical target composition")
	check(Content.HUNT_EVENTS == Registry.HUNT_EVENTS, "ContentDB exposes the registry's canonical incident composition")
	check(Content.ITEM_CATALOG == Dustball.ITEMS, "ContentDB preserves the starter item catalog")
	check(Content.ITEM_CATALOG == Registry.STARTER_ITEM_CATALOG, "ContentDB exposes the registry's starter item catalog")
	check(Content.PLANET_ITEM_CATALOGS == Registry.PLANET_ITEM_CATALOGS, "ContentDB exposes the registry's primary item catalogs")
	check(Content.SECONDARY_ITEM_CATALOGS == Registry.SECONDARY_ITEM_CATALOGS, "ContentDB exposes the registry's secondary item catalogs")
	check(Content.TARGETS.slice(0, 4) == Dustball.TARGETS, "ContentDB preserves all four starter targets in canonical order")
	check(Content.HUNT_EVENTS.slice(0, 2) == Dustball.EVENTS, "ContentDB preserves both starter incidents in canonical order")
	check([Content.TARGETS[0].power, Content.TARGETS[1].power, Content.TARGETS[2].power, Content.TARGETS[3].power] == [11, 16, 23, 28], "starter combat anchors remain unchanged")
	check([Content.TARGETS[0].credits, Content.TARGETS[1].credits, Content.TARGETS[2].credits, Content.TARGETS[3].credits] == [38, 58, 88, 138], "starter economy anchors remain unchanged")

	check(Content.PLANETS.slice(1, 3) == [Congelaria.PLANET, Micelia.PLANET], "ContentDB preserves the next two planets in canonical order")
	check(Content.TARGETS.slice(4, 8) == Congelaria.TARGETS, "ContentDB preserves all four Congelaria targets")
	check(Content.TARGETS.slice(8, 12) == Micelia.TARGETS, "ContentDB preserves all four Micelia targets")
	check(Content.HUNT_EVENTS.slice(2, 4) == Congelaria.EVENTS, "ContentDB preserves both Congelaria incidents")
	check(Content.HUNT_EVENTS.slice(4, 6) == Micelia.EVENTS, "ContentDB preserves both Micelia incidents")
	check(Content.PLANET_ITEM_CATALOGS.congelaria_sa == Congelaria.ITEMS, "Congelaria primary equipment remains canonical")
	check(Content.PLANET_ITEM_CATALOGS.micelia_404 == Micelia.ITEMS, "Micelia primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.congelaria_sa == Congelaria.SECONDARY_ITEMS, "Congelaria helmet catalog remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.micelia_404 == Micelia.SECONDARY_ITEMS, "Micelia helmet and gloves catalogs remain canonical")
	check(Content.loot_slots_for_planet("congelaria_sa") == ["weapon", "weapon", "weapon", "armor", "armor", "helmet"], "Congelaria introduces only helmets")
	check(Content.loot_slots_for_planet("micelia_404") == ["weapon", "weapon", "weapon", "armor", "armor", "helmet", "gloves"], "Micelia adds gloves without removing helmets")
	check([Congelaria.TARGETS[0].power, Congelaria.TARGETS[3].power, Micelia.TARGETS[0].power, Micelia.TARGETS[3].power] == [31, 45, 47, 69], "mid-campaign combat anchors remain unchanged")

	check(Content.PLANETS.slice(3, 5) == [FerroVelho.PLANET, Cassino.PLANET], "ContentDB preserves both intermediate planets in canonical order")
	check(Content.TARGETS.slice(12, 16) == FerroVelho.TARGETS, "ContentDB preserves all four Ferro-Velho targets")
	check(Content.TARGETS.slice(16, 20) == Cassino.TARGETS, "ContentDB preserves all four Cassino targets")
	check(Content.HUNT_EVENTS.slice(6, 8) == FerroVelho.EVENTS, "ContentDB preserves both Ferro-Velho incidents")
	check(Content.HUNT_EVENTS.slice(8, 10) == Cassino.EVENTS, "ContentDB preserves both Cassino incidents")
	check(Content.PLANET_ITEM_CATALOGS.ferro_velho_omega == FerroVelho.ITEMS, "Ferro-Velho primary equipment remains canonical")
	check(Content.PLANET_ITEM_CATALOGS.cassino_quasar == Cassino.ITEMS, "Cassino primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.ferro_velho_omega == FerroVelho.SECONDARY_ITEMS, "Ferro-Velho secondary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.cassino_quasar == Cassino.SECONDARY_ITEMS, "Cassino secondary equipment remains canonical")
	var intermediate_slots := ["weapon", "weapon", "weapon", "armor", "armor", "helmet", "gloves", "boots"]
	check(Content.loot_slots_for_planet("ferro_velho_omega") == intermediate_slots, "Ferro-Velho completes the first universal secondary loadout")
	check(Content.loot_slots_for_planet("cassino_quasar") == intermediate_slots, "Cassino deepens the loadout without opening a surprise slot")
	check(FerroVelho.SECONDARY_ITEMS.keys() == Cassino.SECONDARY_ITEMS.keys(), "intermediate packs expose the same secondary slot surface")
	check([FerroVelho.TARGETS[0].power, FerroVelho.TARGETS[3].power, Cassino.TARGETS[0].power, Cassino.TARGETS[3].power] == [69, 90, 96, 124], "intermediate combat anchors remain unchanged")

	check(Content.PLANETS.slice(5, 7) == [Aeropolis.PLANET, ArquivoAbissal.PLANET], "ContentDB preserves both late planets in canonical order")
	check(Content.TARGETS.slice(20, 24) == Aeropolis.TARGETS, "ContentDB preserves all four Aeropolis targets")
	check(Content.TARGETS.slice(24, 28) == ArquivoAbissal.TARGETS, "ContentDB preserves all four Arquivo Abissal targets")
	check(Content.HUNT_EVENTS.slice(10, 12) == Aeropolis.EVENTS, "ContentDB preserves both Aeropolis incidents")
	check(Content.HUNT_EVENTS.slice(12, 14) == ArquivoAbissal.EVENTS, "ContentDB preserves both Arquivo Abissal incidents")
	check(Content.PLANET_ITEM_CATALOGS.aeropolis_penhora == Aeropolis.ITEMS, "Aeropolis primary equipment remains canonical")
	check(Content.PLANET_ITEM_CATALOGS.arquivo_abissal_n9 == ArquivoAbissal.ITEMS, "Arquivo Abissal primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.aeropolis_penhora == Aeropolis.SECONDARY_ITEMS, "Aeropolis rig catalog remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.arquivo_abissal_n9 == ArquivoAbissal.SECONDARY_ITEMS, "Arquivo Abissal implant catalog remains canonical")
	check(Aeropolis.SECONDARY_ITEMS.keys() == ["rig"], "Aeropolis exposes only its late rig branch")
	check(ArquivoAbissal.SECONDARY_ITEMS.keys() == ["implant"], "Arquivo Abissal exposes only its late implant branch")
	check(Content.loot_slots_for_planet("aeropolis_penhora") == ["weapon", "weapon", "weapon", "armor", "armor", "rig", "rig"], "Aeropolis weights rigs without leaking intermediate slots")
	check(Content.loot_slots_for_planet("arquivo_abissal_n9") == ["weapon", "weapon", "weapon", "armor", "armor", "implant", "implant"], "Arquivo Abissal weights implants without leaking rigs")
	check([Aeropolis.TARGETS[0].power, Aeropolis.TARGETS[3].power, ArquivoAbissal.TARGETS[0].power, ArquivoAbissal.TARGETS[3].power] == [136, 175, 190, 245], "late combat anchors remain unchanged")

	check(Content.PLANETS[7] == Verdantia.PLANET, "the level-50 planet follows Arquivo Abissal in canonical order")
	check(Content.TARGETS.slice(28, 32) == Verdantia.TARGETS, "ContentDB exposes all four Verdantia targets")
	check(Content.HUNT_EVENTS.slice(14, 16) == Verdantia.EVENTS, "ContentDB exposes both Verdantia incidents")
	check(Content.PLANET_ITEM_CATALOGS.verdantia_patenteada == Verdantia.ITEMS, "Verdantia primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.verdantia_patenteada == Verdantia.SECONDARY_ITEMS, "Verdantia boot catalog remains canonical")
	check(Content.loot_slots_for_planet("verdantia_patenteada") == ["weapon", "weapon", "weapon", "armor", "armor", "boots", "boots"], "Verdantia deepens boots without opening Rift-only slots")
	check([Verdantia.TARGETS[0].power, Verdantia.TARGETS[3].power] == [250, 282], "level-50 combat anchors are explicit")
	check(Verdantia.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "new target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[8] == Caldeira.PLANET, "the level-60 planet follows Verdantia in canonical order")
	check(Content.TARGETS.slice(32, 36) == Caldeira.TARGETS, "ContentDB exposes all four Caldera targets")
	check(Content.HUNT_EVENTS.slice(16, 18) == Caldeira.EVENTS, "ContentDB exposes both Caldera incidents")
	check(Content.PLANET_ITEM_CATALOGS.caldeira_garantia == Caldeira.ITEMS, "Caldera primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.caldeira_garantia == Caldeira.SECONDARY_ITEMS, "Caldera glove catalog remains canonical")
	check(Content.loot_slots_for_planet("caldeira_garantia") == ["weapon", "weapon", "weapon", "armor", "armor", "gloves", "gloves"], "Caldera deepens gloves without opening Rift-only slots")
	check([Caldeira.TARGETS[0].power, Caldeira.TARGETS[3].power] == [290, 324], "level-60 combat anchors are explicit")
	check(Caldeira.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Caldera target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[9] == CondominioLunar.PLANET, "the level-70 planet follows Caldera in canonical order")
	check(Content.TARGETS.slice(36, 40) == CondominioLunar.TARGETS, "ContentDB exposes all four Lunar Estate targets")
	check(Content.HUNT_EVENTS.slice(18, 20) == CondominioLunar.EVENTS, "ContentDB exposes both Lunar Estate incidents")
	check(Content.PLANET_ITEM_CATALOGS.condominio_lunar_7 == CondominioLunar.ITEMS, "Lunar Estate primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.condominio_lunar_7 == CondominioLunar.SECONDARY_ITEMS, "Lunar Estate helmet catalog remains canonical")
	check(Content.loot_slots_for_planet("condominio_lunar_7") == ["weapon", "weapon", "weapon", "armor", "armor", "helmet", "helmet"], "Lunar Estate deepens helmets without opening Rift-only slots")
	check([CondominioLunar.TARGETS[0].power, CondominioLunar.TARGETS[3].power] == [336, 380], "level-70 combat anchors are explicit")
	check(CondominioLunar.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Lunar Estate target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[10] == NecropoleSolar.PLANET, "the level-80 planet follows Lunar Estate in canonical order")
	check(Content.TARGETS.slice(40, 44) == NecropoleSolar.TARGETS, "ContentDB exposes all four Solar Necropolis targets")
	check(Content.HUNT_EVENTS.slice(20, 22) == NecropoleSolar.EVENTS, "ContentDB exposes both Solar Necropolis incidents")
	check(Content.PLANET_ITEM_CATALOGS.necropole_solar_umbral == NecropoleSolar.ITEMS, "Solar Necropolis primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.necropole_solar_umbral == NecropoleSolar.SECONDARY_ITEMS, "Solar Necropolis rig catalog remains canonical")
	check(Content.loot_slots_for_planet("necropole_solar_umbral") == ["weapon", "weapon", "weapon", "armor", "armor", "rig", "rig"], "Solar Necropolis deepens rigs without opening Rift-only slots")
	check([NecropoleSolar.TARGETS[0].power, NecropoleSolar.TARGETS[3].power] == [392, 444], "level-80 combat anchors are explicit")
	check(NecropoleSolar.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Solar Necropolis target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[11] == CentralTempestades.PLANET, "the level-90 planet follows Solar Necropolis in canonical order")
	check(Content.TARGETS.slice(44, 48) == CentralTempestades.TARGETS, "ContentDB exposes all four Storm Center targets")
	check(Content.HUNT_EVENTS.slice(22, 24) == CentralTempestades.EVENTS, "ContentDB exposes both Storm Center incidents")
	check(Content.PLANET_ITEM_CATALOGS.central_tempestades_24h == CentralTempestades.ITEMS, "Storm Center primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.central_tempestades_24h == CentralTempestades.SECONDARY_ITEMS, "Storm Center implant catalog remains canonical")
	check(Content.loot_slots_for_planet("central_tempestades_24h") == ["weapon", "weapon", "weapon", "armor", "armor", "implant", "implant"], "Storm Center deepens implants without opening Rift-only slots")
	check([CentralTempestades.TARGETS[0].power, CentralTempestades.TARGETS[3].power] == [457, 516], "level-90 combat anchors are explicit")
	check(CentralTempestades.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Storm Center target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[12] == MuseuAmanha.PLANET, "the level-100 planet follows the Storm Center in canonical order")
	check(Content.TARGETS.slice(48, 52) == MuseuAmanha.TARGETS, "ContentDB exposes all four Obsolete Tomorrow targets")
	check(Content.HUNT_EVENTS.slice(24, 26) == MuseuAmanha.EVENTS, "ContentDB exposes both Obsolete Tomorrow incidents")
	check(Content.PLANET_ITEM_CATALOGS.museu_amanha_obsoleto == MuseuAmanha.ITEMS, "Obsolete Tomorrow primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.museu_amanha_obsoleto == MuseuAmanha.SECONDARY_ITEMS, "Obsolete Tomorrow boot catalog remains canonical")
	check(Content.loot_slots_for_planet("museu_amanha_obsoleto") == ["weapon", "weapon", "weapon", "armor", "armor", "boots", "boots"], "Obsolete Tomorrow deepens boots without opening Rift-only slots")
	check([MuseuAmanha.TARGETS[0].power, MuseuAmanha.TARGETS[3].power] == [530, 598], "level-100 combat anchors are explicit")
	check(MuseuAmanha.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Obsolete Tomorrow target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[13] == BibliotecaSilencio.PLANET, "the level-110 planet follows Obsolete Tomorrows in canonical order")
	check(Content.TARGETS.slice(52, 56) == BibliotecaSilencio.TARGETS, "ContentDB exposes all four Taxed Silence targets")
	check(Content.HUNT_EVENTS.slice(26, 28) == BibliotecaSilencio.EVENTS, "ContentDB exposes both Taxed Silence incidents")
	check(Content.PLANET_ITEM_CATALOGS.biblioteca_silencio_taxado == BibliotecaSilencio.ITEMS, "Taxed Silence primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.biblioteca_silencio_taxado == BibliotecaSilencio.SECONDARY_ITEMS, "Taxed Silence glove catalog remains canonical")
	check(Content.loot_slots_for_planet("biblioteca_silencio_taxado") == ["weapon", "weapon", "weapon", "armor", "armor", "gloves", "gloves"], "Taxed Silence deepens gloves without opening Rift-only slots")
	check([BibliotecaSilencio.TARGETS[0].power, BibliotecaSilencio.TARGETS[3].power] == [615, 692], "level-110 combat anchors are explicit")
	check(BibliotecaSilencio.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Taxed Silence target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[14] == ResortHorizonte.PLANET, "the level-120 planet follows Taxed Silence in canonical order")
	check(Content.TARGETS.slice(56, 60) == ResortHorizonte.TARGETS, "ContentDB exposes all four Event Horizon Resort targets")
	check(Content.HUNT_EVENTS.slice(28, 30) == ResortHorizonte.EVENTS, "ContentDB exposes both Event Horizon Resort incidents")
	check(Content.PLANET_ITEM_CATALOGS.resort_horizonte_eventos == ResortHorizonte.ITEMS, "Event Horizon Resort primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.resort_horizonte_eventos == ResortHorizonte.SECONDARY_ITEMS, "Event Horizon Resort helmet catalog remains canonical")
	check(Content.loot_slots_for_planet("resort_horizonte_eventos") == ["weapon", "weapon", "weapon", "armor", "armor", "helmet", "helmet"], "Event Horizon Resort deepens helmets without opening Rift-only slots")
	check([ResortHorizonte.TARGETS[0].power, ResortHorizonte.TARGETS[3].power] == [712, 801], "level-120 combat anchors are explicit")
	check(ResortHorizonte.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Event Horizon Resort target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[15] == TribunalClones.PLANET, "the level-130 planet follows Event Horizon Resort in canonical order")
	check(Content.TARGETS.slice(60, 64) == TribunalClones.TARGETS, "ContentDB exposes all four Unauthorized Clone Court targets")
	check(Content.HUNT_EVENTS.slice(30, 32) == TribunalClones.EVENTS, "ContentDB exposes both Unauthorized Clone Court incidents")
	check(Content.PLANET_ITEM_CATALOGS.tribunal_clones_nao_autorizados == TribunalClones.ITEMS, "Unauthorized Clone Court primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.tribunal_clones_nao_autorizados == TribunalClones.SECONDARY_ITEMS, "Unauthorized Clone Court rig catalog remains canonical")
	check(Content.loot_slots_for_planet("tribunal_clones_nao_autorizados") == ["weapon", "weapon", "weapon", "armor", "armor", "rig", "rig"], "Unauthorized Clone Court deepens rigs without opening Rift-only slots")
	check([TribunalClones.TARGETS[0].power, TribunalClones.TARGETS[3].power] == [823, 925], "level-130 combat anchors are explicit")
	check(TribunalClones.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Unauthorized Clone Court target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[16] == MosteiroGravidade.PLANET, "the level-140 planet follows Unauthorized Clone Court in canonical order")
	check(Content.TARGETS.slice(64, 68) == MosteiroGravidade.TARGETS, "ContentDB exposes all four Reverse Gravity Monastery targets")
	check(Content.HUNT_EVENTS.slice(32, 34) == MosteiroGravidade.EVENTS, "ContentDB exposes both Reverse Gravity Monastery incidents")
	check(Content.PLANET_ITEM_CATALOGS.mosteiro_gravidade_reversa == MosteiroGravidade.ITEMS, "Reverse Gravity Monastery primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.mosteiro_gravidade_reversa == MosteiroGravidade.SECONDARY_ITEMS, "Reverse Gravity Monastery implant catalog remains canonical")
	check(Content.loot_slots_for_planet("mosteiro_gravidade_reversa").count("implant") == 2, "level-140 loot deepens the universal implant slot")
	check([MosteiroGravidade.TARGETS[0].power, MosteiroGravidade.TARGETS[3].power] == [946, 1058], "level-140 combat anchors are explicit")
	check(MosteiroGravidade.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Reverse Gravity Monastery target art remains explicitly assigned to the user asset pipeline")

	check(Content.PLANETS[17] == MercadoMemorias.PLANET, "the level-150 planet follows Reverse Gravity Monastery in canonical order")
	check(Content.TARGETS.slice(68, 72) == MercadoMemorias.TARGETS, "ContentDB exposes all four Used Memory Market targets")
	check(Content.HUNT_EVENTS.slice(34, 36) == MercadoMemorias.EVENTS, "ContentDB exposes both Used Memory Market incidents")
	check(Content.PLANET_ITEM_CATALOGS.mercado_memorias_usadas == MercadoMemorias.ITEMS, "Used Memory Market primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.mercado_memorias_usadas == MercadoMemorias.SECONDARY_ITEMS, "Used Memory Market boot catalog remains canonical")
	check(Content.loot_slots_for_planet("mercado_memorias_usadas").count("boots") == 2, "level-150 loot deepens the universal boot slot")
	check([MercadoMemorias.TARGETS[0].power, MercadoMemorias.TARGETS[3].power] == [1081, 1202], "level-150 combat anchors are explicit")
	check(MercadoMemorias.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Used Memory Market target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[18] == EstaleiroTemporal.PLANET, "the level-160 planet follows Used Memory Market in canonical order")
	check(Content.TARGETS.slice(72, 76) == EstaleiroTemporal.TARGETS, "ContentDB exposes all four Temporal Wreck Shipyard targets")
	check(Content.HUNT_EVENTS.slice(36, 38) == EstaleiroTemporal.EVENTS, "ContentDB exposes both Temporal Wreck Shipyard incidents")
	check(Content.PLANET_ITEM_CATALOGS.estaleiro_naufragios_temporais == EstaleiroTemporal.ITEMS, "Temporal Wreck Shipyard primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.estaleiro_naufragios_temporais == EstaleiroTemporal.SECONDARY_ITEMS, "Temporal Wreck Shipyard glove catalog remains canonical")
	check(Content.loot_slots_for_planet("estaleiro_naufragios_temporais").count("gloves") == 2, "level-160 loot deepens the universal glove slot")
	check([EstaleiroTemporal.TARGETS[0].power, EstaleiroTemporal.TARGETS[3].power] == [1230, 1357], "level-160 combat anchors are explicit")
	check(EstaleiroTemporal.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Temporal Wreck Shipyard target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[19] == BolsaLuas.PLANET, "the level-170 planet follows Temporal Wreck Shipyard in canonical order")
	check(Content.TARGETS.slice(76, 80) == BolsaLuas.TARGETS, "ContentDB exposes all four Fractional Moon Exchange targets")
	check(Content.HUNT_EVENTS.slice(38, 40) == BolsaLuas.EVENTS, "ContentDB exposes both Fractional Moon Exchange incidents")
	check(Content.PLANET_ITEM_CATALOGS.bolsa_luas_fracionadas == BolsaLuas.ITEMS, "Fractional Moon Exchange primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.bolsa_luas_fracionadas == BolsaLuas.SECONDARY_ITEMS, "Fractional Moon Exchange helmet catalog remains canonical")
	check(Content.loot_slots_for_planet("bolsa_luas_fracionadas").count("helmet") == 2, "level-170 loot deepens the universal helmet slot")
	check([BolsaLuas.TARGETS[0].power, BolsaLuas.TARGETS[3].power] == [1388, 1522], "level-170 combat anchors are explicit")
	check(BolsaLuas.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Fractional Moon Exchange target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[20] == FabricaSois.PLANET, "the level-180 planet follows Fractional Moon Exchange in canonical order")
	check(Content.TARGETS.slice(80, 84) == FabricaSois.TARGETS, "ContentDB exposes all four Refurbished Sun Factory targets")
	check(Content.HUNT_EVENTS.slice(40, 42) == FabricaSois.EVENTS, "ContentDB exposes both Refurbished Sun Factory incidents")
	check(Content.PLANET_ITEM_CATALOGS.fabrica_sois_recondicionados == FabricaSois.ITEMS, "Refurbished Sun Factory primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.fabrica_sois_recondicionados == FabricaSois.SECONDARY_ITEMS, "Refurbished Sun Factory rig catalog remains canonical")
	check(Content.loot_slots_for_planet("fabrica_sois_recondicionados").count("rig") == 2, "level-180 loot deepens the universal rig slot")
	check([FabricaSois.TARGETS[0].power, FabricaSois.TARGETS[3].power] == [1557, 1702], "level-180 combat anchors are explicit")
	check(FabricaSois.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Refurbished Sun Factory target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[21] == ClinicaPlanetas.PLANET, "the level-190 planet follows Refurbished Sun Factory in canonical order")
	check(Content.TARGETS.slice(84, 88) == ClinicaPlanetas.TARGETS, "ContentDB exposes all four Discontinued Planet Clinic targets")
	check(Content.HUNT_EVENTS.slice(42, 44) == ClinicaPlanetas.EVENTS, "ContentDB exposes both Discontinued Planet Clinic incidents")
	check(Content.PLANET_ITEM_CATALOGS.clinica_planetas_descontinuados == ClinicaPlanetas.ITEMS, "Discontinued Planet Clinic primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.clinica_planetas_descontinuados == ClinicaPlanetas.SECONDARY_ITEMS, "Discontinued Planet Clinic implant catalog remains canonical")
	check(Content.loot_slots_for_planet("clinica_planetas_descontinuados").count("implant") == 2, "level-190 loot deepens the universal implant slot")
	check([ClinicaPlanetas.TARGETS[0].power, ClinicaPlanetas.TARGETS[3].power] == [1740, 1896], "level-190 combat anchors are explicit")
	check(ClinicaPlanetas.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Discontinued Planet Clinic target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[22] == CorreioMinhoca.PLANET, "the level-200 planet follows Discontinued Planet Clinic in canonical order")
	check(Content.TARGETS.slice(88, 92) == CorreioMinhoca.TARGETS, "ContentDB exposes all four Wormhole Post targets")
	check(Content.HUNT_EVENTS.slice(44, 46) == CorreioMinhoca.EVENTS, "ContentDB exposes both Wormhole Post incidents")
	check(Content.PLANET_ITEM_CATALOGS.correio_buracos_minhoca == CorreioMinhoca.ITEMS, "Wormhole Post primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.correio_buracos_minhoca == CorreioMinhoca.SECONDARY_ITEMS, "Wormhole Post boot catalog remains canonical")
	check(Content.loot_slots_for_planet("correio_buracos_minhoca").count("boots") == 2, "level-200 loot deepens the universal boot slot")
	check([CorreioMinhoca.TARGETS[0].power, CorreioMinhoca.TARGETS[3].power] == [1936, 2104], "level-200 combat anchors are explicit")
	check(CorreioMinhoca.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Wormhole Post target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[23] == AquarioOceanos.PLANET, "the level-210 planet follows Wormhole Post in canonical order")
	check(Content.TARGETS.slice(92, 96) == AquarioOceanos.TARGETS, "ContentDB exposes all four Confiscated Oceans Aquarium targets")
	check(Content.HUNT_EVENTS.slice(46, 48) == AquarioOceanos.EVENTS, "ContentDB exposes both Confiscated Oceans Aquarium incidents")
	check(Content.PLANET_ITEM_CATALOGS.aquario_oceanos_confiscados == AquarioOceanos.ITEMS, "Confiscated Oceans Aquarium primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.aquario_oceanos_confiscados == AquarioOceanos.SECONDARY_ITEMS, "Confiscated Oceans Aquarium glove catalog remains canonical")
	check(Content.loot_slots_for_planet("aquario_oceanos_confiscados").count("gloves") == 2, "level-210 loot deepens the universal glove slot")
	check([AquarioOceanos.TARGETS[0].power, AquarioOceanos.TARGETS[3].power] == [2145, 2323], "level-210 combat anchors are explicit")
	check(AquarioOceanos.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Confiscated Oceans Aquarium target art remains explicitly assigned to the user asset pipeline")
	check(Content.PLANETS[24] == CentralSonhos.PLANET, "the level-220 planet follows Confiscated Oceans Aquarium in canonical order")
	check(Content.TARGETS.slice(96, 100) == CentralSonhos.TARGETS, "ContentDB exposes all four Repossessed Dreams Center targets")
	check(Content.HUNT_EVENTS.slice(48, 50) == CentralSonhos.EVENTS, "ContentDB exposes both Repossessed Dreams Center incidents")
	check(Content.PLANET_ITEM_CATALOGS.central_sonhos_penhorados == CentralSonhos.ITEMS, "Repossessed Dreams Center primary equipment remains canonical")
	check(Content.SECONDARY_ITEM_CATALOGS.central_sonhos_penhorados == CentralSonhos.SECONDARY_ITEMS, "Repossessed Dreams Center helmet catalog remains canonical")
	check(Content.loot_slots_for_planet("central_sonhos_penhorados").count("helmet") == 2, "level-220 loot deepens the universal helmet slot")
	check([CentralSonhos.TARGETS[0].power, CentralSonhos.TARGETS[3].power] == [2370, 2564], "level-220 combat anchors are explicit")
	check(CentralSonhos.TARGETS.all(func(target): return str(target.get("visual_delivery", "")) == "pending_user_asset"), "Repossessed Dreams Center target art remains explicitly assigned to the user asset pipeline")

	var forged := Dustball.PACK.duplicate(true)
	forged.targets.pop_back()
	check(not PackContract.is_valid(forged), "incomplete planet packs are rejected")
	forged = Dustball.PACK.duplicate(true)
	forged.events[0].planet_id = "other_world"
	check(not PackContract.is_valid(forged), "cross-planet incident leakage is rejected")
	forged = Dustball.PACK.duplicate(true)
	forged.targets[0].id = "../unsafe"
	check(not PackContract.is_valid(forged), "unsafe content ids are rejected")
	forged = Dustball.PACK.duplicate(true)
	forged.events = "not_an_array"
	check(not PackContract.is_valid(forged), "malformed top-level sections fail closed")
	forged = Dustball.PACK.duplicate(true)
	forged.secondary_items = {"helmet": "not_an_array"}
	check(not PackContract.is_valid(forged), "malformed secondary catalogs fail closed")
	forged = Dustball.PACK.duplicate(true)
	forged.targets[0].boss = true
	forged.targets[3].erase("boss")
	check(not PackContract.is_valid(forged), "planet bosses are reserved for tier three")

	if failures == 0:
		print("PASS: all twenty-five current planet packs preserve canonical content and slot progression")
	quit(1 if failures > 0 else 0)


func check(condition: bool, message: String) -> void:
	if not condition:
		failures += 1
		printerr("FAIL: %s" % message)
