class_name BackendContentManifestRules
extends RefCounted

const Registry = preload("res://scripts/content/content_pack_registry.gd")
const Content = preload("res://scripts/content_db.gd")
const Missions = preload("res://scripts/mission_rules.gd")
const Classes = preload("res://scripts/class_rules.gd")
const EnemyProfiles = preload("res://scripts/enemy_profile_rules.gd")

const SCHEMA_VERSION := 1


static func manifest() -> Dictionary:
	var planets: Array[Dictionary] = []
	var targets: Array[Dictionary] = []
	for pack_script in Registry.PACK_SCRIPTS:
		var planet: Dictionary = pack_script.PLANET
		var target_ids: Array[String] = []
		for target in pack_script.TARGETS:
			target_ids.append(str(target.id))
			targets.append({
				"id": str(target.id),
				"planet_id": str(target.planet_id),
				"rank": int(target.get("rank", 0)),
				"chapter_tier": int(target.get("chapter_tier", 0)),
				"boss": bool(target.get("boss", false)),
				"enemy_profile_id": EnemyProfiles.profile_id_for(target),
			})
		planets.append({
			"id": str(planet.id),
			"unlock_level": int(planet.unlock_level),
			"travel_duration": int(planet.travel_duration),
			"target_ids": target_ids,
		})
	var approaches: Array[Dictionary] = []
	for approach in Content.CONTRACT_APPROACHES:
		var exported := {}
		for key in ["id", "balance_version", "duration_mult", "power_mult", "defense_mult", "health_mult", "frontier_health_bonus", "planet_health_step", "late_power_mult", "late_defense_mult", "late_health_mult", "credits_mult", "xp_mult", "scrap_reward"]:
			if approach.has(key):
				exported[key] = approach[key]
		approaches.append(exported)
	var roles: Array[Dictionary] = []
	for role in Missions.ROLES:
		roles.append({"id": str(role.id), "pressure_mult": float(role.pressure_mult), "reward_mult": float(role.reward_mult)})
	var classes: Array[Dictionary] = []
	for definition in Classes.DEFINITIONS:
		classes.append({
			"id": str(definition.id),
			"primary_attribute": str(definition.primary_attribute),
			"effects": definition.effects.duplicate(true),
		})
	var enemy_profiles := {}
	for profile_id in EnemyProfiles.DEFINITIONS:
		var exported_profile := {}
		for key in ["opening_damage_multiplier", "defense_bypass_multiplier", "damage_reduction_piercing", "counter_damage_multiplier", "attack_roll_bonus_multiplier"]:
			if EnemyProfiles.DEFINITIONS[profile_id].has(key):
				exported_profile[key] = EnemyProfiles.DEFINITIONS[profile_id][key]
		enemy_profiles[profile_id] = exported_profile
	var core := {
		"schema_version": SCHEMA_VERSION,
		"planets": planets,
		"targets": targets,
		"roles": roles,
		"approaches": approaches,
		"classes": classes,
		"enemy_profiles": enemy_profiles,
		"rules": {
			"base_attribute_value": 10,
			"daily_hunt_fuel": 100,
			"late_blend_start": Content.CONTRACT_APPROACH_LATE_BLEND_START,
			"late_blend_end": Content.CONTRACT_APPROACH_LATE_BLEND_END,
			"early_travel_bands": Missions.EARLY_TRAVEL_BANDS.duplicate(true),
			"max_mission_fuel_cost": Missions.MAX_MISSION_FUEL_COST,
		},
	}
	var hashing := HashingContext.new()
	hashing.start(HashingContext.HASH_SHA256)
	hashing.update(JSON.stringify(core).to_utf8_buffer())
	var digest: String = hashing.finish().hex_encode()
	core["content_hash"] = digest
	return core


static func render_typescript() -> String:
	return "// Generated by tools/generate_backend_content_manifest.gd. Do not edit.\nconst CG_CONTENT_MANIFEST: any = %s;\n" % JSON.stringify(manifest())
